services:
  client:
    build: ./client
    ports:
      - 8080:5173
    command: npm run dev
  server:
    build: ./server
    ports:
      - 5050:5050
    command: python app.py
    volumes:
      - ./server:/usr/app
