services:
  client:
    build: ./client
    ports:
      - 8080:5173
    command: npm run dev
  server:
    build: ./server
    ports:
      - 5050:5050
    command: python app.py

  db:
    image: bitnami/mysql:8.0.36
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_DATABASE=mydatabase
    ports:
      - 5442:5442
