services:
  client:
    build: ./client
    ports:
      - 8080:5173
    command: npm run dev
  server:
    build: ./server
    ports:
      - 5050:5050
    command: python app.py
    develop:
      watch:
        - action: sync
          path: ./client
          target: ./usr/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
