services:
  client:
    build: ./client
    ports:
      - 8080:5173
    command: npm run dev
  server:
    build: ./server
    ports:
      - 5050:5050
    command: python app.py

  db:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_PASSWORD=mypassword
      - POSTGRESQL_USERNAME=myuser
      - POSTGRESQL_DATABASE=mydatabase
    ports:
      - 5432:5432
